-- =============================================================================
-- Migration: Fix Centers Schema
-- Fixes: missing name, orphaned CENTER_TYPES, duplicate geo fields,
--        phone type, typo, CENTER_CHARACTERISTICS normalization
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. CENTERS: add name (campo crítico faltante)
-- ---------------------------------------------------------------------------
ALTER TABLE "CENTERS"
  ADD COLUMN name VARCHAR(255) NOT NULL DEFAULT '';

-- Once data is seeded, remove the default to enforce NOT NULL strictly
-- ALTER TABLE "CENTERS" ALTER COLUMN name DROP DEFAULT;

-- ---------------------------------------------------------------------------
-- 2. CENTERS: connect CENTER_TYPES (tabla huérfana → FK)
-- ---------------------------------------------------------------------------
ALTER TABLE "CENTERS"
  ADD COLUMN id_type BIGINT REFERENCES "CENTER_TYPES"(id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- 3. CENTERS: add email + website (campos básicos faltantes)
-- ---------------------------------------------------------------------------
ALTER TABLE "CENTERS"
  ADD COLUMN email    VARCHAR(255),
  ADD COLUMN website  TEXT;

-- ---------------------------------------------------------------------------
-- 4. CENTERS: remove duplicate address fields (ya están en ADDRESSES)
-- ---------------------------------------------------------------------------
ALTER TABLE "CENTERS"
  DROP COLUMN IF EXISTS street,
  DROP COLUMN IF EXISTS street_num;

-- ---------------------------------------------------------------------------
-- 5. CENTERS: remove position geometry (la geo vive en ADDRESSES.geo_location)
-- ---------------------------------------------------------------------------
ALTER TABLE "CENTERS"
  DROP COLUMN IF EXISTS position;

-- ---------------------------------------------------------------------------
-- 6. ADDRESSES: fix typo geo_locatio → geo_location
-- ---------------------------------------------------------------------------
ALTER TABLE "ADDRESSES"
  RENAME COLUMN geo_locatio TO geo_location;

-- ---------------------------------------------------------------------------
-- 7. PHONES: fix type numeric → varchar (teléfonos con +34, 00, etc.)
-- ---------------------------------------------------------------------------
ALTER TABLE "PHONES"
  ALTER COLUMN phone TYPE VARCHAR(20) USING phone::text;

-- ---------------------------------------------------------------------------
-- 8. CENTER_CHARACTERISTICS: normalizar → catálogo + many-to-many
--
--    ANTES: CENTER_CHARACTERISTICS(id, name TEXT, id_center)  ← texto libre
--    DESPUÉS:
--      CHARACTERISTIC_TYPES(id, name)  ← catálogo único
--      CENTER_CHARACTERISTICS(id, id_center, id_characteristic)  ← junction
-- ---------------------------------------------------------------------------

-- 8.1 Tabla catálogo de características
CREATE TABLE IF NOT EXISTS "CHARACTERISTIC_TYPES" (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT characteristic_types_name_unique UNIQUE (name)
);

ALTER TABLE "CHARACTERISTIC_TYPES" ENABLE ROW LEVEL SECURITY;

-- 8.2 Reemplazar columna name por FK en CENTER_CHARACTERISTICS
ALTER TABLE "CENTER_CHARACTERISTICS"
  DROP COLUMN IF EXISTS name,
  ADD COLUMN id_characteristic BIGINT REFERENCES "CHARACTERISTIC_TYPES"(id) ON DELETE CASCADE;

-- Constraint para evitar duplicados (un centro no puede tener la misma característica dos veces)
ALTER TABLE "CENTER_CHARACTERISTICS"
  ADD CONSTRAINT center_characteristics_unique UNIQUE (id_center, id_characteristic);
