-- =============================================================================
-- Migration: Postal codes lookup cache
-- Permite resolver CP → ciudad → provincia → comunidad sin llamar a Mapbox.
-- Dataset: ~11.000 registros. Fuente: Geonames ES (gratuito, dominio público).
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Tabla de códigos postales (relación N:M con CITIES)
--    Un CP puede abarcar varios municipios (ej. zonas rurales).
--    Un municipio puede tener varios CPs (ej. ciudades grandes).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "POSTAL_CODES" (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        CHAR(5)     NOT NULL,
  id_city     BIGINT      NOT NULL REFERENCES "CITIES"(id) ON DELETE CASCADE,
  CONSTRAINT postal_codes_unique UNIQUE (code, id_city)
);

ALTER TABLE "POSTAL_CODES" ENABLE ROW LEVEL SECURITY;

-- Índice para búsqueda rápida por código
CREATE INDEX idx_postal_codes_code ON "POSTAL_CODES" (code);

-- ---------------------------------------------------------------------------
-- 2. Vista materializada para el lookup completo desde el frontend
--    Query del frontend: SELECT * FROM postal_code_lookup WHERE code = '46400'
--    Retorna: city, province, community → rellena el form sin API call
-- ---------------------------------------------------------------------------
CREATE MATERIALIZED VIEW postal_code_lookup AS
SELECT
  pc.code                AS postal_code,
  c.id                   AS city_id,
  c.name                 AS city,
  p.id                   AS province_id,
  p.name                 AS province,
  co.id                  AS community_id,
  co.name                AS community
FROM "POSTAL_CODES"    pc
JOIN "CITIES"          c  ON c.id  = pc.id_city
JOIN "PROVINCES"       p  ON p.id  = c.id_province
JOIN "COMMUNITIES"     co ON co.id = p.id_community
ORDER BY pc.code, c.name;

CREATE UNIQUE INDEX idx_postal_code_lookup ON postal_code_lookup (postal_code, city_id);

-- Para refrescar cuando se agregan datos:
-- REFRESH MATERIALIZED VIEW CONCURRENTLY postal_code_lookup;

-- ---------------------------------------------------------------------------
-- NOTA: seed de datos
-- Cargar el dataset de Geonames ES en COMMUNITIES, PROVINCES, CITIES y
-- POSTAL_CODES. Archivo gratuito:
-- https://download.geonames.org/export/zip/ES.zip
-- Columnas: country_code, postal_code, place_name, admin_name1 (comunidad),
--           admin_code1, admin_name2 (provincia), admin_code2, ...
-- Script de carga sugerido: scripts/seed_postal_codes.ts
-- ---------------------------------------------------------------------------
